# I haven't figured this out yet. I don't know the write env vars to use codeberg's package registry, and even without that, I get this error:
# https://ci.codeberg.org/repos/15442/pipeline/2/errors
# could not load config from forge: configFetcher: fallback did not find config: user does not exist [uid: 0, name: ] user does not exist [uid: 0, name: ] user does not exist [uid: 0, name: ]

# when:
#   - event: push
#     branch: main
#     path:
#       include:
#         - .woodpecker/publish-charts.yaml
#         - devopscoop
#         - pipeline.sh
#   - event: pull_request
#     branch: main
#     path:
#       include:
#         - .woodpecker/publish-charts.yaml
#         - devopscoop
#         - pipeline.sh
#
# steps:
#   - name: build-charts
#     image: alpine/helm:3.17.2
#     commands:
#       - ./pipeline.sh
#   - name: publish-charts
#     when:
#       - evaluate: 'CI_PIPELINE_EVENT == "push"'
#     commands:
#       - helm_registry="codeberg.org"
#       - helm_username="me"
#       - helm_password="redacted"
#       - git_repo_owner="devopscoop"
#       - ./pipeline.sh push
