when:
  - event: push
    branch: main
    path:
      include:
        - .woodpecker/publish-charts.yaml
        - devopscoop
        - pipeline.sh
  - event: pull_request
    branch: main
    path:
      include:
        - .woodpecker/publish-charts.yaml
        - devopscoop
        - pipeline.sh

steps:
  - name: build-charts
    image: alpine/helm:3.17.2
    commands:
      - ./pipeline.sh
  - name: publish-charts
    when:
      - evaluate: 'CI_PIPELINE_EVENT == "push" && I_FIGURED_HOW_TO_USE_PACKAGES == "true"'
    commands:
      - helm_registry="codeberg.org"
      - helm_username="me"
      - helm_password="redacted"
      - git_repo_owner="devopscoop"
      - ./pipeline.sh push
